---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ansible-eda
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ansible-eda
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["pods", "deployments", "services", "jobs", "deployments/scale"]
    verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ansible-eda
  namespace: default
roleRef:
  kind: Role
  name: ansible-eda
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ansible-eda
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ansible-eda
    app.kubernetes.io/version: 1.0.0
  name: ansibleeda
spec:
  ports:
    - name: http
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app.kubernetes.io/name: ansible-eda
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: ansible-eda
  name: ansible-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/name: ansible-eda
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/name: ansible-eda
    spec:
      serviceAccountName: ansible-eda
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/rhdevelopers/ansible-eda:replicas
          imagePullPolicy: Always
          name: ansible-eda
          ports:
            - containerPort: 5001
              name: http
              protocol: TCP
