# This Container file provides a base EDA image that contains the necessary
# dependencies to create Ansible EDA container images that run rulebooks

FROM registry.access.redhat.com/ubi9-minimal

RUN microdnf install java-17 python3 gcc python3-devel -y && microdnf clean all && python -m ensurepip --upgrade && pip3 install ansible ansible-rulebook asyncio aiokafka aiohttp aiosignal kubernetes requests ansible-runner wheel

# Configure Java and Ansible environment. Java is required by EDA!
ENV JAVA_HOME="/usr/lib/jvm/jre-17"
ENV ANSIBLE_HOME="/home/ansible/.ansible"
ENV ANSIBLE_CONFIG="/home/ansible/.ansible/ansible.cfg"

# Create ansible user and configure permissions on their homedir to support
# arbitrary user IDs https://docs.openshift.com/container-platform/4.13/openshift_images/create-images.html#use-uid_create-images
USER root
RUN groupadd --gid 1001 ansible \
  && useradd --uid 1001 --gid ansible --shell /bin/bash --create-home ansible

# Make a tmp dir for Ansible to avoid permission issues on OpenShift
RUN mkdir -p /home/ansible/.ansible-tmp
RUN chown -R 1001:0 /home/ansible/.ansible-tmp && \
    chmod -R ug+rwx /home/ansible/.ansible-tmp

# Copy in a base Ansible config to avoid issues with tmp dir permissions
COPY --chown=1001:1001 ansible.cfg /home/ansible/.ansible/ansible.cfg

USER ansible
